### ISSUE TITLE
Disabling a schema returns BODY_FORMAT_EXCEPTION error

### ISSUE THREAD

**Issue by MaartenEvenepoel** [ExtraHorizon/javascript-sdk#490]
## Description
I tried to disable a schema using the SDK but got a BODY_FORMAT_EXCEPTION error returned. As far as I could find the disable schema call does not require a request body, yet this error was still produced.

## Steps to Reproduce
1. Create and authenticate client
2. Attempt to disable an existing schema
3. The following error is produced: 

```
[Error]: The provided body does not have the expected format
    at Function.createFromHttpError (/home/maarten/tools/data-service-shema-tools/node_modules/@extrahorizon/javascript-sdk/build/index.cjs.js:1:5280)
    at Ya (/home/maarten/tools/data-service-shema-tools/node_modules/@extrahorizon/javascript-sdk/build/index.cjs.js:1:57895)
    at /home/maarten/tools/data-service-shema-tools/node_modules/@extrahorizon/javascript-sdk/build/index.cjs.js:1:62107
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.disable (/home/maarten/tools/data-service-shema-tools/node_modules/@extrahorizon/javascript-sdk/build/index.cjs.js:1:32216)
    at async /home/maarten/tools/data-service-shema-tools/build/index.js:18:5 {
  qName: 'BODY_FORMAT_EXCEPTION',
  status: 400,
  statusText: 'Bad Request',
  error: 'BODY_FORMAT_EXCEPTION',
  request: {
    url: '/data/v1/61b7515f46bd7466d681f2b6/disable',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'X-User-Agent': 'Node/v16.10.0 OS/linux-x64 SDK/5.2.0-dev.160',
      Authorization: 'OAuth oauth_consumer_key="...", oauth_ ...  oauth_version="1.0"}',
      'User-Agent': 'axios/0.21.4',
      'Content-Length': 4
    },
    method: 'post',
    payloadData: 'null'
  },
  response: {
    code: 22,
    name: 'BODY_FORMAT_EXCEPTION',
    message: 'The provided body does not have the expected format'
  }
}

```

## Code example

```typescript

  // Setup and authenticate client here
...
  await extrahorizonSDK.data.schemas.disable('61b7515f46bd7466d681f2b6');
```

## Specifications

- Version: 5.2.0-dev.160
- Platform: Linux
- Endpoint or service affected:

**Comment by jensdev** [comment]
Hi @MaartenEvenepoel I am unable to reproduce this. This seems a little strange: `payloadData: 'null'` but when I try to disable a schema even with data I don't get this error with Node 16.10, Axios 0.21.4. Could you send me the application you trying to this on? 
Could you with the branch `fix/disable-schema`. You can install it via
```sh
yarn add git+ssh://github.com/ExtraHorizon/javascript-sdk#fix/disable-schema`
```

**Comment by MaartenEvenepoel** [comment]
Hi @jensdev. Good news. The `fix/disable-schema` you provided seems to solve the problem. Thanks!
