### ISSUE TITLE
Uploading a file with tags results in an error

### ISSUE THREAD

**Issue by wwaaijer-fib** [ExtraHorizon/javascript-sdk#527]
## Description
I don't seem to be able to upload a file with tags.

## Steps to Reproduce

```typescript
const tags = ['foo', 'bar'];
await sdk.files.create(name, file, { tags })
```

Results into an error from `form-data`:

```
Error: Arrays are not supported.
    at FormData.append (C:\Users\Wilco\Documents\git\measurement-file-extractor-task\node_modules\form-data\lib\form_data.js:67:17)
    at Object.create (C:\Users\Wilco\Documents\git\measurement-file-extractor-task\node_modules\@extrahorizon\javascript-sdk\build\index.cjs.js:1:36649)
    at uploadMeasurement (C:\Users\Wilco\Documents\git\measurement-file-extractor-task\build\steps\upload.js:27:52)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.handler (C:\Users\Wilco\Documents\git\measurement-file-extractor-task\build\index.js:45:34)

```

## Specifications

- Version: `6.0.0`
- Platform: Node.js
- Endpoint or service affected: `files.create`

**Comment by wwaaijer-fib** [comment]
I only need 1 tag for my current use case. So currently I can circumvent the issue by casting my single value to `any`:
```ts
await sdk.files.create(name, file, { tags: 'foo' as any })
```
Not a blocking issue for me now. But I'm going to guess others might want to be able to add multiple tags.

**Comment by jensdev** [comment]
Made a PR.

Related to https://github.com/form-data/form-data#void-append-string-field-mixed-value--mixed-options-
